import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { SidebarProvider } from "@/components/ui/sidebar";
import AppSidebar from "@/components/common/Sidebar";
import Header from "@/components/common/Header";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Task Flow | Brandsquare Agency",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full dark scrollbar-thin scrollbar-track-transparent scrollbar-thumb-primary/30",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        inter.variable,
      )}
    >
      <body className="min-h-full overflow-x-hidden flex flex-col">
        <SidebarProvider>
          <AppSidebar />
          <main className="bg-[#0A0A0A] w-full m-2 rounded-2xl">
            <Header />
            <div className="p-2 flex flex-col justify-center">{children}</div>
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
